"""add rol and local columns to credentials

Revision ID: cfa28c3cd7c3
Revises: 
Create Date: 2025-07-17 12:52:32.906210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'cfa28c3cd7c3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('promo_burger')
    # op.drop_table('sin')
    # op.drop_table('user_client')
    # op.drop_table('promo_drinks')
    # op.drop_table('coupons')
    # op.drop_table('drinks')
    # op.drop_table('fries')
    # op.drop_table('burger_main_imgs')
    # op.drop_table('order_combos')
    # op.drop_table('burger')
    # op.drop_table('promos')
    # op.drop_table('order_promos')
    # op.drop_table('combo_fries')
    # op.drop_table('promo_fries')
    # op.drop_table('combos')
    # op.drop_table('extras')
    # op.drop_table('combo_burger')
    # op.drop_table('credentials')
    op.alter_column('order_burger', 'id_order_burger',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order_burger', 'id_order',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    # op.drop_constraint('fk_order_burger_id_burger', 'order_burger', type_='foreignkey')
    op.alter_column('order_burger', 'id_burger',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    # op.create_index(op.f('ix_order_burger_id_order_burger'), 'order_burger', ['id_order_burger'], unique=False)
    # op.drop_constraint('fk_order_coupons_id_order', 'order_coupons', type_='foreignkey')
    op.alter_column('order_coupons', 'id_order',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    # op.drop_constraint('fk_order_coupons_id_coupons', 'order_coupons', type_='foreignkey')
    op.alter_column('order_coupons', 'id_coupons',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    # op.create_index(op.f('ix_order_coupons_id_order_coupons'), 'order_coupons', ['id_order_coupons'], unique=False)
    op.alter_column('order_drinks', 'id_order_drinks',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order_drinks', 'id_order',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('order_drinks', 'id_drinks',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=50),
               existing_nullable=True)
    # op.create_index(op.f('ix_order_drinks_id_order_drinks'), 'order_drinks', ['id_order_drinks'], unique=False)
    op.drop_constraint('fk_order_drinks_id_drinks', 'order_drinks', type_='foreignkey')
    # op.drop_constraint('fk_order_drinks_id_order', 'order_drinks', type_='foreignkey')
    op.alter_column('order_extra', 'id_order_extra',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order_extra', 'id_order',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('order_extra', 'id_extra',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    # op.create_index(op.f('ix_order_extra_id_order_extra'), 'order_extra', ['id_order_extra'], unique=False)
    op.drop_constraint('fk_order_extra_id_extra', 'order_extra', type_='foreignkey')
    op.drop_constraint('fk_order_extra_id_order', 'order_extra', type_='foreignkey')
    op.alter_column('order_fries', 'id_order_fries',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order_fries', 'id_order',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('order_fries', 'id_fries',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    # op.create_index(op.f('ix_order_fries_id_order_fries'), 'order_fries', ['id_order_fries'], unique=False)
    op.drop_constraint('fk_order_fries_id_fries', 'order_fries', type_='foreignkey')
    op.drop_constraint('fk_order_fries_id_order', 'order_fries', type_='foreignkey')
    op.alter_column('order_sin', 'id_order_sin',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order_sin', 'id_order',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('order_sin', 'id_sin',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    # op.create_index(op.f('ix_order_sin_id_order_sin'), 'order_sin', ['id_order_sin'], unique=False)
    op.drop_constraint('fk_order_sin_id_sin', 'order_sin', type_='foreignkey')
    op.drop_constraint('fk_order_sin_id_order', 'order_sin', type_='foreignkey')
    op.alter_column('order_user_client', 'id_order_user_client',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('order_user_client', 'id_order',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('order_user_client', 'id_user_client',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=True)
    # op.create_index(op.f('ix_order_user_client_id_order_user_client'), 'order_user_client', ['id_order_user_client'], unique=False)
    op.drop_constraint('fk_order_user_client_id_user_client', 'order_user_client', type_='foreignkey')
    op.drop_constraint('fk_order_user_client_id_order', 'order_user_client', type_='foreignkey')
    op.drop_table_comment(
        'order_user_client',
        existing_comment='\t\t\t',
        schema=None
    )
    op.alter_column('orders', 'id_order',
               existing_type=mysql.CHAR(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('orders', 'order_notes',
               existing_type=mysql.VARCHAR(length=45),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.create_index(op.f('ix_orders_id_order'), 'orders', ['id_order'], unique=False)
    op.drop_column('orders', 'sin')
    op.drop_column('orders', 'burgers')
    op.drop_column('orders', 'fries')
    op.drop_column('orders', 'extra')
    op.drop_column('orders', 'drinks')
    op.drop_column('orders', 'promos')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('promos', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('orders', sa.Column('drinks', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('orders', sa.Column('extra', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('orders', sa.Column('fries', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('orders', sa.Column('burgers', mysql.VARCHAR(length=45), nullable=True))
    op.add_column('orders', sa.Column('sin', mysql.VARCHAR(length=45), nullable=True))
    op.drop_index(op.f('ix_orders_id_order'), table_name='orders')
    op.alter_column('orders', 'order_notes',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('orders', 'id_order',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=False)
    op.create_table_comment(
        'order_user_client',
        '\t\t\t',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key(op.f('fk_order_user_client_id_user_client'), 'order_user_client', 'user_client', ['id_user_client'], ['id_user_client'])
    op.drop_index(op.f('ix_order_user_client_id_order_user_client'), table_name='order_user_client')
    op.alter_column('order_user_client', 'id_user_client',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_user_client', 'id_order',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_user_client', 'id_order_user_client',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_order_sin_id_sin'), 'order_sin', 'sin', ['id_sin'], ['id_sin'])
    op.drop_index(op.f('ix_order_sin_id_order_sin'), table_name='order_sin')
    op.alter_column('order_sin', 'id_sin',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_sin', 'id_order',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_sin', 'id_order_sin',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_order_fries_id_fries'), 'order_fries', 'fries', ['id_fries'], ['id_fries'])
    op.drop_index(op.f('ix_order_fries_id_order_fries'), table_name='order_fries')
    op.alter_column('order_fries', 'id_fries',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_fries', 'id_order',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_fries', 'id_order_fries',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_order_extra_id_extra'), 'order_extra', 'extras', ['id_extra'], ['id_extras'])
    op.drop_index(op.f('ix_order_extra_id_order_extra'), table_name='order_extra')
    op.alter_column('order_extra', 'id_extra',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_extra', 'id_order',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_extra', 'id_order_extra',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_order_drinks_id_drinks'), 'order_drinks', 'drinks', ['id_drinks'], ['id_drinks'])
    op.drop_index(op.f('ix_order_drinks_id_order_drinks'), table_name='order_drinks')
    op.alter_column('order_drinks', 'id_drinks',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=45),
               existing_nullable=True)
    op.alter_column('order_drinks', 'id_order',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_drinks', 'id_order_drinks',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_order_coupons_id_coupons'), 'order_coupons', 'coupons', ['id_coupons'], ['id_coupons'])
    op.drop_index(op.f('ix_order_coupons_id_order_coupons'), table_name='order_coupons')
    op.alter_column('order_coupons', 'id_coupons',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_coupons', 'id_order',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_coupons', 'id_order_coupons',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=False)
    op.create_foreign_key(op.f('fk_order_burger_id_burger'), 'order_burger', 'burger', ['id_burger'], ['id_burger'])
    op.drop_index(op.f('ix_order_burger_id_order_burger'), table_name='order_burger')
    op.alter_column('order_burger', 'id_burger',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_burger', 'id_order',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=True)
    op.alter_column('order_burger', 'id_order_burger',
               existing_type=sa.String(length=50),
               type_=mysql.CHAR(length=50),
               existing_nullable=False)
    op.create_table('credentials',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=210), nullable=False),
    sa.Column('local', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('rol', mysql.VARCHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('combo_burger',
    sa.Column('id_combo_burger', mysql.CHAR(length=50), nullable=False),
    sa.Column('id_combo', mysql.CHAR(length=50), nullable=True),
    sa.Column('id_burger', mysql.CHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_burger'], ['burger.id_burger'], name=op.f('fk_combo_burger_id_burger')),
    sa.ForeignKeyConstraint(['id_combo'], ['combos.id_combos'], name=op.f('fk_combo_burger_id_combo')),
    sa.PrimaryKeyConstraint('id_combo_burger'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('extras',
    sa.Column('id_extras', mysql.CHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('aditional_price', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id_extras'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('combos',
    sa.Column('id_combos', mysql.CHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('burger', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('drinks', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('fries', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id_combos'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('promo_fries',
    sa.Column('id_promo_fries', mysql.CHAR(length=50), nullable=False),
    sa.Column('id_promo', mysql.CHAR(length=50), nullable=True),
    sa.Column('id_fries', mysql.CHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_fries'], ['fries.id_fries'], name=op.f('promo_fries_ibfk_2')),
    sa.ForeignKeyConstraint(['id_promo'], ['promos.id_promos'], name=op.f('promo_fries_ibfk_1')),
    sa.PrimaryKeyConstraint('id_promo_fries'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('combo_fries',
    sa.Column('id_combo_fries', mysql.CHAR(length=50), nullable=False),
    sa.Column('id_combo', mysql.CHAR(length=50), nullable=True),
    sa.Column('id_fries', mysql.CHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_combo'], ['combos.id_combos'], name=op.f('fk_combo_fries_id_combo')),
    sa.ForeignKeyConstraint(['id_fries'], ['fries.id_fries'], name=op.f('fk_combo_fries_id_fries')),
    sa.PrimaryKeyConstraint('id_combo_fries'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order_promos',
    sa.Column('id_order_promos', mysql.CHAR(length=50), nullable=False),
    sa.Column('id_order', mysql.CHAR(length=50), nullable=True),
    sa.Column('id_promos', mysql.CHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id_order'], name=op.f('order_promos_ibfk_1')),
    sa.ForeignKeyConstraint(['id_promos'], ['promos.id_promos'], name=op.f('order_promos_ibfk_2')),
    sa.PrimaryKeyConstraint('id_order_promos'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('promos',
    sa.Column('id_promos', mysql.CHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('burger', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('drinks', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('fries', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('day', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('quantity', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id_promos'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('burger',
    sa.Column('id_burger', mysql.CHAR(length=50), nullable=False),
    sa.Column('size', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('price', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('stock', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('favorite', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('ingredients', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_burger'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('order_combos',
    sa.Column('id_order_combos', mysql.CHAR(length=50), nullable=False),
    sa.Column('id_order', mysql.CHAR(length=50), nullable=True),
    sa.Column('id_combos', mysql.CHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_combos'], ['combos.id_combos'], name=op.f('fk_order_combos_id_combos')),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id_order'], name=op.f('fk_order_combos_id_order')),
    sa.PrimaryKeyConstraint('id_order_combos'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('burger_main_imgs',
    sa.Column('id', mysql.CHAR(length=50), nullable=False),
    sa.Column('burger_id', mysql.CHAR(length=50), nullable=True),
    sa.Column('url', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['burger_id'], ['burger.id_burger'], name=op.f('burger_main_imgs_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('fries',
    sa.Column('id_fries', mysql.CHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('size', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('description', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('stock', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('favourite', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_fries'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('drinks',
    sa.Column('id_drinks', mysql.CHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('size', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('price', mysql.FLOAT(), nullable=True),
    sa.Column('stock', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('favourite', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_drinks'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('coupons',
    sa.Column('id_coupons', mysql.CHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('value', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id_coupons'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('promo_drinks',
    sa.Column('id_promo_drinks', mysql.CHAR(length=50), nullable=False),
    sa.Column('id_promo', mysql.CHAR(length=50), nullable=True),
    sa.Column('id_drinks', mysql.CHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_drinks'], ['drinks.id_drinks'], name=op.f('promo_drinks_ibfk_2')),
    sa.ForeignKeyConstraint(['id_promo'], ['promos.id_promos'], name=op.f('promo_drinks_ibfk_1')),
    sa.PrimaryKeyConstraint('id_promo_drinks'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_client',
    sa.Column('id_user_client', mysql.CHAR(length=50), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('phone', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('password', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('locality', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('direction', mysql.VARCHAR(length=45), nullable=True),
    sa.Column('notes', mysql.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id_user_client'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sin',
    sa.Column('id_sin', mysql.CHAR(length=50), nullable=False),
    sa.Column('name', mysql.CHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id_sin'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('promo_burger',
    sa.Column('id_promo_burger', mysql.CHAR(length=50), nullable=False),
    sa.Column('id_promo', mysql.CHAR(length=50), nullable=True),
    sa.Column('id_burger', mysql.CHAR(length=50), nullable=True),
    sa.ForeignKeyConstraint(['id_burger'], ['burger.id_burger'], name=op.f('promo_burger_ibfk_2')),
    sa.ForeignKeyConstraint(['id_promo'], ['promos.id_promos'], name=op.f('promo_burger_ibfk_1')),
    sa.PrimaryKeyConstraint('id_promo_burger'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
